#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT

# To include tags for git files and composer packages:
{ git ls-files & find vendor -type f -name '*.php'; } | \
    ctags --tag-relative -L - -f "$$.tags"
    mv "$$.tags" "tags"

# To include tags for only git files:
# git ls-files | \
#   ctags --tag-relative -L - -f "$$.tags"
#   mv "$$.tags" "tags"
